
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: next-app-router
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - knative-serving/knative-ingress-gateway # Assuming standard Knative setup
  http:

  - match:
    - uri:
        exact: "/"
    rewrite:
      authority: next-index.default.svc.cluster.local
    route:
    - destination:
        host: next-index.default.svc.cluster.local


  - match:
    - uri:
        exact: "/_global-error"
    rewrite:
      authority: next-global-error.default.svc.cluster.local
    route:
    - destination:
        host: next-global-error.default.svc.cluster.local


  - match:
    - uri:
        exact: "/_not-found"
    rewrite:
      authority: next-not-found.default.svc.cluster.local
    route:
    - destination:
        host: next-not-found.default.svc.cluster.local


  - match:
    - uri:
        exact: "/audit"
    rewrite:
      authority: next-audit.default.svc.cluster.local
    route:
    - destination:
        host: next-audit.default.svc.cluster.local


  - match:
    - uri:
        exact: "/dashboard"
    rewrite:
      authority: next-dashboard.default.svc.cluster.local
    route:
    - destination:
        host: next-dashboard.default.svc.cluster.local


  - match:
    - uri:
        exact: "/favicon.ico"
    rewrite:
      authority: next-favicon-ico.default.svc.cluster.local
    route:
    - destination:
        host: next-favicon-ico.default.svc.cluster.local


  - match:
    - uri:
        exact: "/setup"
    rewrite:
      authority: next-setup.default.svc.cluster.local
    route:
    - destination:
        host: next-setup.default.svc.cluster.local


  - match:
    - uri:
        exact: "/users"
    rewrite:
      authority: next-users.default.svc.cluster.local
    route:
    - destination:
        host: next-users.default.svc.cluster.local

