
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: next-app-router
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - knative-serving/knative-ingress-gateway # Assuming standard Knative setup
  http:

  - match:
    - uri:
        exact: "/"
    - uri:
        exact: "/_global-error"
    - uri:
        exact: "/_not-found"
    - uri:
        exact: "/audit"
    - uri:
        exact: "/dashboard"
    - uri:
        exact: "/favicon.ico"
    - uri:
        exact: "/setup"
    - uri:
        exact: "/users"
    rewrite:
      authority: next-index.default.svc.cluster.local
    route:
    - destination:
        host: next-index.default.svc.cluster.local

