# This rule is not used by the project kn-next-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.kn-next.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kn-next-operator
    app.kubernetes.io/managed-by: kustomize
  name: nextapp-admin-role
rules:
- apiGroups:
  - apps.kn-next.dev
  resources:
  - nextapps
  verbs:
  - '*'
- apiGroups:
  - apps.kn-next.dev
  resources:
  - nextapps/status
  verbs:
  - get
